# Generated by Django 5.2.8 on 2025-12-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('semester', models.CharField(max_length=20)),
                ('subjectreqd', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('semester', models.CharField(default='Unknown', max_length=20)),
                ('subject', models.CharField(default='Unknown', max_length=50)),
                ('subjectcode', models.CharField(default='Unknown', max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('accountnumber', models.CharField(default='Not Provided', max_length=20)),
                ('bankqr', models.ImageField(default='Not Provided', upload_to='Tutor_profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.tutee')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.tutor')),
            ],
        ),
    ]
