# Generated by Django 5.2.8 on 2025-12-24 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_tutee',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_tutor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Tutee', 'Tutee')], default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='TuteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('subjectreqd', models.CharField(default='Unknown', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='tutee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.tuteeprofile'),
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('semester', models.CharField(default='Unknown', max_length=20)),
                ('subjectcode', models.CharField(default='Unknown', max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('accountnumber', models.CharField(default='Not Provided', max_length=20)),
                ('bankqr', models.ImageField(blank=True, null=True, upload_to='tutor_profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.tutorprofile'),
        ),
        migrations.DeleteModel(
            name='Tutee',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
