# Generated by Django 5.2.8 on 2025-12-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutee',
            name='password',
            field=models.CharField(default='notset', max_length=128),
        ),
        migrations.AddField(
            model_name='tutor',
            name='password',
            field=models.CharField(default='notset', max_length=128),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bankqr',
            field=models.ImageField(blank=True, null=True, upload_to='Tutor_profile/'),
        ),
    ]
