# Generated by Django 5.2.8 on 2025-12-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tutee_password_tutor_password_alter_tutor_bankqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutee',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutee',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
