# Generated by Django 5.2.8 on 2026-01-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tutee_profiles/'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/pictures/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tuteeprofile',
            name='semester',
            field=models.CharField(default='Not Specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='bankqr',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subject',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
