# Generated by Django 5.2.8 on 2026-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tuteeprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=10)),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Temporary Signup',
                'verbose_name_plural': 'Temporary Signups',
            },
        ),
    ]
