# Generated by Django 5.2.8 on 2026-01-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_temporarysignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='bankqr',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/qr/'),
        ),
    ]
