# Generated by Django 5.2.8 on 2026-01-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_availabilityslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuteeprofile',
            name='subjectreqd',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='bankqr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Engineering')], default='Computer Science', max_length=50),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Unavailable', 'Unavailable')], default='Available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.tutorprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('tutor', 'date', 'start_time')},
            },
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
    ]
