# Generated by Django 5.2.8 on 2026-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tuteeprofile_subjectreqd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='subjectcode',
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Engineering', 'Computer Engineering')], default='Computer Science', max_length=50),
        ),
        migrations.AddField(
            model_name='tuteeprofile',
            name='year',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='year',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='tuteeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/pictures/'),
        ),
        migrations.AlterField(
            model_name='tuteeprofile',
            name='semester',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
