# Generated by Django 5.2.8 on 2026-01-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tutorprofile_subjectcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='accountnumber',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='rate',
            field=models.CharField(default='Not Provided', max_length=20),
        ),
    ]
