# Generated by Django 5.2.8 on 2026-01-21 02:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 21, 2, 34, 48, 909586, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default=datetime.date(2026, 1, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Unavailable', 'Unavailable')], default='Available', max_length=15),
        ),
        migrations.AddField(
            model_name='availability',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.tutorprofile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('tutor', 'date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tutor',
        ),
    ]
