# Generated by Django 5.2.8 on 2026-01-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_booking_completed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
